# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "floating_point_1_synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {Synth 8-524}  -string {{ERROR: [Synth 8-524] part-select [271:256] out of range of prefix 'A_row_packed' [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dot_product_engine.sv:28]}}  -suppress 
set_msg_config  -id {Synth 8-196}  -string {{ERROR: [Synth 8-196] conditional expression could not be resolved to a constant [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dot_product_engine.sv:24]}}  -suppress 
set_msg_config  -id {Synth 8-6156}  -string {{ERROR: [Synth 8-6156] failed synthesizing module 'dot_product_engine' [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dot_product_engine.sv:2]}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Synth 8-6156}  -string {{ERROR: [Synth 8-6156] failed synthesizing module 'top_dot_product_engine' [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/top_dot_product_engine.sv:2]}}  -suppress 
set_msg_config  -id {Synth 8-6859}  -string {{CRITICAL WARNING: [Synth 8-6859] multi-driven net on pin Q with 1st driver pin 'dyn_sipo_inst/shift_reg_reg[255]/Q' [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dynamic_sipo.sv:18]}}  -suppress 
set_msg_config  -id {Synth 8-6859}  -string {{CRITICAL WARNING: [Synth 8-6859] multi-driven net on pin Q with 2nd driver pin 'GND' [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dynamic_sipo.sv:18]}}  -suppress 
set_msg_config  -id {Synth 8-6858}  -string {{CRITICAL WARNING: [Synth 8-6858] multi-driven net Q is connected to at least one constant driver which has been preserved, other driver is ignored [/home/hp/Desktop/hassan_ai/dpe_git/dot_product_integration/dot_product_sim.srcs/sources_1/new/dynamic_sipo.sv:18]}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku5p-ffvb676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.cache/wt [current_project]
set_property parent.project_path /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /Desktop/hassan_ai/dpe_git/dpe_v1.3/dot_product_integration/ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property used_in_implementation false [get_files -all /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1 -new_name floating_point_1 -ip [get_ips floating_point_1]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top floating_point_1 -part xcku5p-ffvb676-2-i -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix floating_point_1_ floating_point_1.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ floating_point_1_stub.v
 lappend ipCachedFiles floating_point_1_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ floating_point_1_stub.vhdl
 lappend ipCachedFiles floating_point_1_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ floating_point_1_sim_netlist.v
 lappend ipCachedFiles floating_point_1_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ floating_point_1_sim_netlist.vhdl
 lappend ipCachedFiles floating_point_1_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp floating_point_1.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips floating_point_1]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all floating_point_1_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef floating_point_1.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file floating_point_1_utilization_synth.rpt -pb floating_point_1_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1.dcp /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1.dcp /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1_stub.v /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1_stub.vhdl /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1_sim_netlist.v /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.runs/floating_point_1_synth_1/floating_point_1_sim_netlist.vhdl /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.ip_user_files/ip/floating_point_1]} {
  catch { 
    file copy -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.v /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.ip_user_files/ip/floating_point_1
  }
}

if {[file isdir /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.ip_user_files/ip/floating_point_1]} {
  catch { 
    file copy -force /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.gen/sources_1/ip/floating_point_1/floating_point_1_stub.vhdl /home/umer-javed/Music/dot_product/dot_product_sim/dot_product_sim.ip_user_files/ip/floating_point_1
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "floating_point_1_synth_1" END { }
