#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 10 23:06:26 PKT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_axi_dpe_wrapper_behav -key {Behavioral:sim_1:Functional:tb_top_axi_dpe_wrapper} -tclbatch tb_top_axi_dpe_wrapper.tcl -view /home/umer-javed/Pictures/upload/project_simulation/project_simulation.srcs/sim_1/imports/dot_product_sim/tb_top_axi_dpe_wrapper_behav.wcfg -log simulate.log"
xsim tb_top_axi_dpe_wrapper_behav -key {Behavioral:sim_1:Functional:tb_top_axi_dpe_wrapper} -tclbatch tb_top_axi_dpe_wrapper.tcl -view /home/umer-javed/Pictures/upload/project_simulation/project_simulation.srcs/sim_1/imports/dot_product_sim/tb_top_axi_dpe_wrapper_behav.wcfg -log simulate.log

